name: Cross-Platform Build

on:
  push:
    branches: [dev]

jobs:
  macos-build:
    name: MacOS Build
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      # 构建 macOS Release
      - name: Build macOS Release
        run: flutter build macos --release

      # 安装 create-dmg 工具
      - name: Install create-dmg
        run: npm install -g create-dmg

      # 打包 .app 成 DMG（跳过签名）
      - name: Package .app into DMG
        run: |
          cd build/macos/Build/Products/Release/
          # 获取 .app 名称
          appName=$(ls -d *.app | head -n 1)
          # 生成 DMG 文件名（不带版本号也可以，最终用 ls 获取）
          dmgName="${appName%.app}.dmg"
          echo "Packaging $appName into $dmgName"

          # 打包 DMG，跳过签名
          create-dmg "$appName" \
            --overwrite \
            --no-version-in-filename \
            --dmg-title "${appName%.app}" \
            --no-code-sign

      # 上传 DMG
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-dmg
          path: build/macos/Build/Products/Release/*.dmg
          retention-days: 5
