name: Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.29.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Universal APK
        run: flutter build apk

      - name: Move Universal APK
        run: |
          mkdir -p artifacts/universal
          mv build/app/outputs/apk/release/app-release.apk artifacts/universal/

      - name: Build Split APKs
        run: flutter build apk --split-per-abi

      - name: Move Split APKs
        run: |
          mkdir -p artifacts/split
          mv build/app/outputs/apk/release/*.apk artifacts/split/

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: artifacts/
          retention-days: 5
