name: Cross-Platform Build

on:
  push:
    branches: [dev]

jobs:
  macos-build:
    name: MacOS Build
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: Package .app into DMG
        run: |
          cd build/macos/Build/Products/Release/

          # 创建临时目录
          mkdir dmg_temp
          cp -R *.app dmg_temp/
          cd dmg_temp

          # 获取 .app 名称并去掉空格
          appName="$(ls -d *.app | head -n 1)"
          safeAppName="${appName// /_}"
          mv "$appName" "$safeAppName"

          # DMG 输出路径
          dmgName="../${safeAppName%.app}.dmg"
          echo "Packaging $safeAppName into $dmgName"

          # 生成 DMG
          create-dmg "$safeAppName" \
            --overwrite \
            --dmg-title "${safeAppName%.app}" \
            --volname "${safeAppName%.app}" \
            --icon-size 120 \
            "$dmgName"

      # 7️⃣ 上传 DMG
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-dmg
          path: build/macos/Build/Products/Release/*.dmg
          retention-days: 5
