name: Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.29.2"

      # 创建 key.properties 并注入 Secrets
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      # 将 Base64 编码的密钥库文件解码并保存
      - name: Set up keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android/app/upload-keystore.jks

      - name: Install dependencies
        run: flutter pub get

      # 构建带签名的 APK
      - name: Build Universal APK
        run: flutter build apk --release

      - name: Move Universal APK
        run: |
          mkdir -p artifacts/universal
          mv build/app/outputs/apk/release/app-release.apk artifacts/universal/

      - name: Build Split APKs
        run: flutter build apk --split-per-abi

      - name: Move Split APKs
        run: |
          mkdir -p artifacts/split
          mv build/app/outputs/apk/release/*.apk artifacts/split/

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: artifacts/
          retention-days: 5