name: Cross-Platform Build

on:
  push:
    branches: [dev]

jobs:
  macos-build:
    name: MacOS Build
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      # 构建 macOS Release
      - name: Build macOS Release
        run: flutter build macos --release

      # 安装 create-dmg 工具
      - name: Install create-dmg
        run: npm install -g create-dmg

      # 打包 .app 成 DMG（带拖拽安装效果）
      - name: Package .app into DMG
        run: |
          cd build/macos/Build/Products/Release/
          appName=$(ls -d *.app | head -n 1)
          dmgName="${appName%.app}.dmg"
          echo "packaging $appName into $dmgName"

          # 新建一个临时目录，避免同名冲突
          mkdir -p dmg_out
          create-dmg "$appName" \
            --overwrite \
            --dmg-title "${appName%.app}" \
            --volname "${appName%.app}" \
            --icon-size 120 \
            --no-code-sign \
            --out "dmg_out/$dmgName"

          # 把生成的 DMG 移回 Release 目录，方便 upload-artifact 抓取
          mv "dmg_out/$dmgName" .

      # 上传 DMG
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-dmg
          path: build/macos/Build/Products/Release/*.dmg
          retention-days: 5
