name: IOS Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build ipa
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - run: sudo xcode-select --switch /Applications/Xcode_16.0.app
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          mkdir -p /Users/runner/work/haka_comic/haka_comic/build/ios/iphoneos/Payload
          mv /Users/runner/work/haka_comic/haka_comic/build/ios/iphoneos/Runner.app /Users/runner/work/haka_comic/haka_comic/build/ios/iphoneos/Payload
          cd /Users/runner/work/haka_comic/haka_comic/build/ios/iphoneos/
          zip -r no-codesign-ios.ipa Payload
      - name: Add version to filename
        run: |
          mv build/ios/iphoneos/no-codesign-ios.ipa artifacts/no-codesign-ios.ipa
      - uses: actions/upload-artifact@v4
        with:
          name: ios_build
          path: artifacts/
          retention-days: 5

      - name: Send Email
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: IOS Build
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Build job of ${{ github.repository }} completed successfully!
          attachments: artifacts/*.ipa
