name: Cross-Platform Build

on:
  push:
    branches: [dev]

jobs:
  macos-build:
    name: MacOS Build
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      # 构建 macOS Release
      - name: Build macOS Release
        run: flutter build macos --release

      # 安装 create-dmg 工具
      - name: Install create-dmg
        run: npm install -g create-dmg

      # 打包 .app 成 DMG（带拖拽安装效果）
      - name: Package .app into DMG
        run: |
          cd build/macos/Build/Products/Release/
          # 获取 .app 名称
          appName="$(ls -d *.app | head -n 1)"
          # 临时去掉空格
          safeAppName="${appName// /_}"
          mv "$appName" "$safeAppName"
          dmgName="${safeAppName%.app}.dmg"
          echo "Packaging $safeAppName into $dmgName"
          create-dmg "$safeAppName" \
            --overwrite \
            --dmg-title "${safeAppName%.app}" \
            --volname "${safeAppName%.app}" \
            --icon-size 120 \
            "./$dmgName"

      # 上传 DMG
      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-dmg
          path: build/macos/Build/Products/Release/*.dmg
          retention-days: 5
