name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: '要构建的分支 (例如：main, develop)'
        required: true
        default: 'main'

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64

      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - run: flutter pub get

      - name: Build unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos/
          zip -r no-codesign-ios.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/no-codesign-ios.ipa
          retention-days: 5