name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: '要构建的分支 (例如：main, develop)'
        required: true
        default: 'feat/thumbnail-navigation' # 默认值已更改为您指定的分支

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64

      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - run: flutter pub get

      - name: Build IPA and Capture Log
        id: build
        shell: bash
        run: |
          set -o pipefail
          flutter build ios --release --no-codesign 2>&1 | tee build.log

      - name: Package IPA
        if: success()
        run: |
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            mkdir -p build/ios/iphoneos/Payload
            mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
            cd build/ios/iphoneos/
            zip -r no-codesign-ios.ipa Payload
          else
            echo "Error: Runner.app file not found, packaging failed."
            exit 1
          fi

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-log-${{ github.event.inputs.target_branch }}
          path: build.log
          retention-days: 1

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/no-codesign-ios.ipa
          retention-days: 5
