name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: '要构建的分支 (例如：main)'
        required: true
        default: 'main'

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64

      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - run: flutter pub get

      - name: Build IPA and Capture Log
        id: build
        shell: bash
        run: |
          set -o pipefail
          BUILD_COMMAND="flutter build ios --release --no-codesign"
          LOG_FILE="build.log"
          
          # 运行构建，将所有输出写入 build.log 并显示在终端
          $BUILD_COMMAND 2>&1 | tee $LOG_FILE || true
          
          # 检查构建是否成功：查看日志中是否有 "** BUILD FAILED **" 关键词
          if grep -q "** BUILD FAILED **" $LOG_FILE; then
            echo "build_status=failed" >> $GITHUB_OUTPUT
            echo "构建失败，将上传错误日志。"
            # 即使构建失败，Shell 也继续执行，但我们必须设置状态
          else
            echo "build_status=success" >> $GITHUB_OUTPUT
            echo "构建成功，将继续打包 IPA 并上传。"
          fi

          # 修复 Artifact 名称错误：在 Shell 中进行替换
          # 将 target_branch 中的所有 / 替换为 -
          CLEAN_BRANCH_NAME=$(echo "${{ github.event.inputs.target_branch }}" | tr / -)
          echo "clean_branch_name=$CLEAN_BRANCH_NAME" >> $GITHUB_OUTPUT # 设置新的输出变量

      - name: Package IPA (Success Path)
        if: steps.build.outputs.build_status == 'success'
        run: |
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            mkdir -p build/ios/iphoneos/Payload
            mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
            cd build/ios/iphoneos/
            zip -r no-codesign-ios.ipa Payload
          else
            echo "Error: Runner.app file not found, packaging failed."
            exit 1
          fi

      - name: Upload Error Log (Failure Path)
        if: failure() # 仅在 Job 失败时上传日志
        uses: actions/upload-artifact@v4
        with:
          # 修复 Artifact 命名：使用 Shell 步骤设置的 clean_branch_name 变量
          name: ios-build-error-log-${{ steps.build.outputs.clean_branch_name }}
          path: build.log
          retention-days: 1

      - name: Upload IPA
        if: success() # 仅在 Job 成功时上传 IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/no-codesign-ios.ipa
          retention-days: 5
